version: "3.7"

services:
  app:
    container_name: vue-todo-frontend
    image: vue-todo-frontend
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - '8080:8080'
